# name: deploy-docusaurus

# on:
#   push:
#     branches: [master]
#   pull_request:
#     branches: [master]

#   # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

<<<<<<< HEAD
# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   publish:
#     runs-on: ubuntu-latest
#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - name: Check out repo
#         uses: actions/checkout@v2
#       # Node is required for npm
#       - name: Set up Node
#         uses: actions/setup-node@v2
#         with:
#           node-version: "16"
#       # Install and build Docusaurus website
#       - name: Build Docusaurus website
#         run: |
#           cd /home/runner/work/hdcx/hdcx
#           npm install react-player
#           npm install 
#           npm run build
#       - name: Upload ftp
#         if: success()
#         uses: sebastianpopp/ftp-action@releases/v2
#         with:
#           host: ${{ secrets.FTP_SERVER }}
#           user: ${{ secrets.FTP_USERNAME }}
#           password: ${{ secrets.FTP_PASSWORD }}
#           localDir: "build"
#           remoteDir: "www"
#           # options: "--delete --asci"
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
=======
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repo
        uses: actions/checkout@v4
      # Node is required for npm
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      # Install and build Docusaurus website
      - name: Build Docusaurus website
        run: |
          cd /home/runner/work/hdcx/hdcx
          npm install react-player
          npm install 
          npm run build
      - name: Upload ftp
        if: success()
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: "build"
          remoteDir: "www"
          # options: "--delete --asci"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
>>>>>>> origin
